// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

extern int relais_Speed;

#ifdef __cplusplus
extern "C" {
#endif

void Lumiere_rouge(lv_event_t * e);
void Lumiere_vert(lv_event_t * e);
void Lumiere_bleu(lv_event_t * e);
void update_value(lv_event_t * e);
void Speed_relais(lv_event_t * e);
void Activate_relais_once(lv_event_t * e);
void Activate_relais_loop(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
