// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"



extern void setLedBrightness(int r,int v, int b);
extern void get_Value();
extern void relais_once();

extern int redValue;
extern int greenValue;
extern int blueValue;
int relais_Speed=100;
extern int tab_sensor[4];
extern char rfid[12];
char last_rfid[12];
char str2[5];


void Lumiere_rouge(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target(e);
  int slider_value = lv_slider_get_value(slider);  
  redValue =  slider_value*2.55;
  setLedBrightness(redValue,greenValue,blueValue);
}

void Lumiere_vert(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target(e);
  int slider_value = lv_slider_get_value(slider);  
  greenValue = slider_value*2.55;
  setLedBrightness(redValue,greenValue,blueValue);
}

void Lumiere_bleu(lv_event_t * e)
{
  lv_obj_t * slider = lv_event_get_target(e);
  int slider_value = lv_slider_get_value(slider);  
  blueValue = slider_value*2.55;
  setLedBrightness(redValue,greenValue,blueValue);
}

void update_value(lv_event_t * e)
{
 unsigned long currentMillis = millis();
  get_Value(tab_sensor);
	lv_label_set_text(ui_Label14,itoa(tab_sensor[0], str2,10));
  lv_label_set_text(ui_Label13,itoa(tab_sensor[1], str2,10));
  lv_label_set_text(ui_Label12, itoa(tab_sensor[2], str2,10));
  lv_label_set_text(ui_Label7, itoa(tab_sensor[3], str2,10));
  // if (rfid == last_rfid)  {  
  //     lv_label_set_text(ui_Label7, "");
  //     for (int i = 0; i < 12; i++) {
  //          last_rfid[i] = rfid[i];  
  //     }
  //   }
}
void Speed_relais(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target(e);
  int slider_value = lv_slider_get_value(slider);  
  relais_Speed = 100-slider_value;
}

void Activate_relais_once(lv_event_t * e)
{
	relais_once();
}

void Activate_relais_loop(lv_event_t * e)
{
	
}
